# Generated by Django 5.2.7 on 2025-11-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Binary_Tree_Model_v1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.BooleanField(default=False)),
                ('y', models.BooleanField(default=False)),
                ('result', models.CharField(max_length=5)),
            ],
        ),
    ]
