# Generated by Django 5.2.7 on 2025-11-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='binary_tree_model_v1',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
