# Generated by Django 5.2.7 on 2026-01-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_binary_tree_model_v1_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Binary_Tree_Model_v2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(blank=True)),
                ('output', models.TextField(blank=True)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Binary_Tree_Model_v1',
        ),
    ]
